name: Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Test-CLI:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Cache sample WSI
        id: cache-wsi
        uses: actions/cache@v3
        with:
          path: ~/wsi/
          key: sample-wsi
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install WSInfer-CLI
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
          python -m pip install .
      - name: Download sample WSI
        if: steps.cache-wsi.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/wsi
          cd ~/wsi
          Invoke-WebRequest -URI https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs -OutFile CMU-1.svs
          cd -
      - name: Run tests
        # Go to a different directory to test that WSInfer-MIL still finds everything it needs.
        # Test it twice so the second time we get cache hits.
        run: |
          mkdir -p ~/foobar
          cd ~/foobar
          wsinfer-mil run -m kaczmarj/pancancer-tissue-classifier.tcga -i ~/wsi/CMU-1.svs
          wsinfer-mil run -m kaczmarj/pancancer-tissue-classifier.tcga -i ~/wsi/CMU-1.svs
